### PR TITLE
Fix Fl_Check_Browser.{H|cxx} indentation (#121)

### LINKED ISSUE #121: During #116, noticed Fl_Check_Browser needs some whitespace fixups
Albrecht agreed, [see this issue 116 comment](https://github.com/fltk/fltk/pull/116#discussion_r458522494)

Suggestion was to use clang-format, but I decided to take a manual shot at it anyway, and noticed a few oddball things (like ';' at the end of C style comments) that I'm not sure clang would fix, and one small code mod `if (p==0)` vs `if (!p)` that I think improves readability, and a few other non-code things to improve readability.

Patch attached here, too lazy to create a fork and all that.
[Fl_Check_Browser--whitespace-patch.txt](https://github.com/fltk/fltk/files/5012528/Fl_Check_Browser--whitespace-patch.txt)

### PR DESCRIPTION
**Pull request by Albrecht-S**
... and some more whitespace errors as proposed by Greg
... in issue #121: Fl_Check_Browser--whitespace-patch.txt

Fixes #121

### CODE REVIEW

File: src/Fl_Check_Browser.cxx [hunk 1]
```diff
@@ -173,64 +172,64 @@ void Fl_Check_Browser::item_swap(void *a, void *b) {
...
+          X + CHECK_SIZE, cy + CHECK_SIZE, X + CHECK_SIZE, cy);
+  if (i->checked) {
+    int tx = X + 3;
+    int tw = CHECK_SIZE - 4;
+    int d1 = tw / 3;
+    int d2 = tw - d1;
+    int ty = cy + (CHECK_SIZE + d2) / 2 - d1 - 2;
+    for (int n = 0; n < 3; n++, ty++) {
+      fl_line(tx, ty, tx + d1, ty + d1);
+      fl_line(tx + d1, ty + d1, tx + tw - 1, ty + d1 - d2 + 1);
```
Comment (erco77) [inline src/Fl_Check_Browser.cxx:198]: The use of condensed whitespace still seems clearer/more readable to me in the original code for the lines that use it, but I see it's used inconsistently.
If I'd been hand-editing the fixes, I'd probably have fixed only the indenting issues (as they were egregious, lol) and left the whitespace around the variables untouched, esp for the fl_line() functions. But perhaps consistency is best. Hard call.

File: src/Fl_Check_Browser.cxx [hunk 2]
```diff
@@ -300,90 +299,89 @@ int Fl_Check_Browser::remove(int item) {
...
 }
 
 int Fl_Check_Browser::handle(int event) {
   if (event == FL_PUSH) {
     int X, Y, W, H;
     bbox(X, Y, W, H);
-    if (Fl::event_inside(X, Y, W, H))
+    if (Fl::event_inside(X, Y, W, H)) {
       deselect();
+    }
```
Comment (erco77) [inline src/Fl_Check_Browser.cxx:384]: If I were to change anything here, I'd have moved deselect() up to the same line as the event_inside() line, but I think I'd have left the original code if hand editing, just to fix indenting issues.

File: src/Fl_Check_Browser.cxx (hunk 1 above)
Comment (Albrecht-S) [reply src/Fl_Check_Browser.cxx:198]: Personally I like the spaces around operators more because this is better readable for me (and ISTR that Ian said this also).

I left these here for consistency, as you wrote. I looked around in the file and found that this was the style of this file. I suggest to leave this as it is now.

File: src/Fl_Check_Browser.cxx (hunk 2 above)
Comment (Albrecht-S) [reply src/Fl_Check_Browser.cxx:384]: Really? I'm surprised. This change is from your original patch in #121 (https://github.com/fltk/fltk/files/5012528/Fl_Check_Browser--whitespace-patch.txt) - not at all modified by me:
```
   522	 int Fl_Check_Browser::handle(int event) {
   523	   if (event == FL_PUSH) {
   524	     int X, Y, W, H;
   525	     bbox(X, Y, W, H);
   526	-    if (Fl::event_inside(X, Y, W, H))
   527	+    if (Fl::event_inside(X, Y, W, H)) {
   528	       deselect();
   529	+    }
   530	   }
   531	   return Fl_Browser_::handle(event);
```

I agree that the curly braces are not necessary here, but I would still leave this on two lines as it was in the original code.

**Comment by Albrecht-S** [comment]
@erco77 Can we merge and close this and #121, please? See my comments above.

I suggest to either leave it as-is and merge this PR or to revert the 2nd change [commented above](https://github.com/fltk/fltk/pull/132#discussion_r482163320) (curly braces in lines 526-529 of the original patch). I can do it, just drop a final note here. TIA.

**Comment by erco77** [comment]
Ya, go ahead.. my code comments are just observations.

File: src/Fl_Check_Browser.cxx (hunk 2 above)
Comment (erco77) [reply src/Fl_Check_Browser.cxx:384]: I can't remember -- usually I add braces like that for one liners only when I'm debugging, and I either leave it in place if I think more debugging is necessary, or leave them out when done.

When editing fltk code, I often have an image in my head of Bill's general view of keeping code as tight fitting as possible, hence the curly brace coding style and very conservative use of vertical white separation and two space indent. It's all about getting as much code on the page as possible. In the 90's that was a bigger deal than it is now, but I understand the benefits and try to continue to employ them. My code in Fl_Tree.cxx is an example of that; you'll see little vertical white used in the code and lots of one lines for simple if()s. I only use vertical white in FLTK if I think it helps code comprehension for particularly complicated sections.
